### ISSUE TITLE
Todo: write checklist for offboarding/deactivating a chapter

### ISSUE THREAD

**Issue by Mariatta** [pyladies/project-admin-logisitics#4]
It would be great to write down the process and checklist for deactivating a PyLadies chapter.

From PyLadies admin side, these are the things we should do (in order): 
- [ ]  find out the reason
- [ ] offer help/support from global PyLadies
- [ ] ask them to delete related meetup accounts, social media accounts 
- [ ] let PSF accounting know, so they don't continue being in the PSF Meetup Pro network
- [ ] delete the user in google admin
- [ ] update chapter directory

We probably need to create a form that can be filled in by chapter leaders who want to deactivate their chapter.

This form should be linked in kit.pyladies.com.

Should this be a hard delete (actually deleting accounts), or soft-delete (just add note somewhere that this chapter inactive and there is no organizer?)

Open for ideas and pull requests.

**Comment by jackiekazil** [comment]
RE: soft delete versus hard delete -- I think that depends on resources. 
I can't imagine why a soft delete would work in any of these cases. It would be nice for Meetup, but I wouldn't want PSF to continue paying dues. And the email? I would say hard for privacy reasons. Maybe there is a transition, where we have a process to actively recruit a new leader, but if no one steps up the chapter shuts down. 

RE: Deactivating - The one thing I hope we can do is make people feel like it is okay to deactivate a chapter, so they don't feel trapped.
